path: /mnt/windows/Users/Aditya Bhandari/Desktop/code/GitHub/Inscription-character-deciphering-for-Brahmi-script/data/yolo_format
train: images/train
val: images/val
nc: 130
names:
- ğ‘€…
- ğ‘€¢
- ğ‘€¦ğ‘†
- ğ‘€§ğ‘…
- ğ‘€¢ğ‘†
- ğ‘€­ğ‘†
- ğ‘€“ğ‘†
- ğ‘€“ğ‘€¼
- ğ‘€ˆ
- ğ‘€¢ğ‘€¸
- ğ‘€¦
- ğ‘€«ğ‘†
- ğ‘‡
- ğ‘€«ğ‘€¸
- ğ‘€—ğ‘†
- ğ‘€´
- ğ‘€§
- ğ‘€´ğ‘†
- ğ‘€´ğ‘€º
- ğ‘€§ğ‘€º
- ğ‘€ğ‘†
- ğ‘€˜ğ‘€¼
- ğ‘€“
- ğ‘€¯
- ğ‘€˜ğ‘‚
- ğ‘€¬ğ‘†
- ğ‘€¬
- ğ‘€“ğ‘€º
- ğ‘€¦ğ‘€º
- ğ‘€®
- ğ‘€«
- ğ‘€“ğ‘ƒ
- ğ‘€¬ğ‘€½
- ğ‘€¦ğ‘‚
- ğ‘€ğ‘€¼
- ğ‘€­
- ğ‘€§ğ‘€¼
- ğ‘€´ğ‘€½
- ğ‘€˜
- ğ‘€¡
- ğ‘€«ğ‘€¼
- ğ‘€‡
- ğ‘€§ğ‘†
- ğ‘€§ğ‘€¸
- ğ‘€¯ğ‘‚
- ğ‘€®ğ‘†
- ğ‘€˜ğ‘€º
- ğ‘€­ğ‘€º
- ğ‘€“ğ‘„
- ğ‘€¢ğ‘€¼
- ğ‘€¯ğ‘€º
- ğ‘€˜ğ‘€¸
- ğ‘€‰
- ğ‘€­ğ‘ƒ
- ğ‘€
- ğ‘€­ğ‘€¼
- ğ‘€ğ‘€º
- ğ‘€Š
- ğ‘€¡ğ‘€º
- ğ‘€§ğ‘„
- ğ‘€¢ğ‘€»
- ğ‘€¦ğ‘€»
- ğ‘€¬ğ‘€¸
- ğ‘€¦ğ‘ƒ
- ğ‘€
- ğ‘€¯ğ‘€»
- ğ‘€“ğ‘€¸
- ğ‘€ğ‘ƒ
- ğ‘€¬ğ‘€º
- ğ‘€´ğ‘ƒ
- ğ‘€˜ğ‘†
- ğ‘€§ğ‘‚
- ğ‘€®ğ‘ƒ
- ğ‘€¯ğ‘€¸
- ğ‘€¯ğ‘ƒ
- ğ‘€­ğ‘€¸
- ğ‘€¯ğ‘€¼
- ğ‘€†
- ğ‘€‘
- ğ‘€´ğ‘€¸
- ğ‘€´ğ‘€¼
- ğ‘€¢ğ‘‚
- ğ‘€¢ğ‘€º
- ğ‘€¡ğ‘†
- ğ‘€®ğ‘€º
- ğ‘€¦ğ‘„
- ğ‘€¡ğ‘€¼
- ğ‘€«ğ‘‚
- ğ‘€¬ğ‘€¼
- ğ‘€¢ğ‘ƒ
- ğ‘€«ğ‘€»
- ğ‘€®ğ‘‚
- ğ‘€“ğ‘€½
- ğ‘€¡ğ‘‚
- ğ‘€“ğ‘‚
- ğ‘€§ğ‘€½
- ğ‘€«ğ‘€º
- ğ‘€ğ‘€¸
- ğ‘€˜ğ‘ƒ
- ğ‘€¡ğ‘ƒ
- ğ‘€­ğ‘‚
- ğ‘€«ğ‘ƒ
- ğ‘€®ğ‘€¼
- ğ‘€¦ğ‘€¸
- ğ‘€¬ğ‘ƒ
- ğ‘€­ğ‘€½
- ğ‘€¦ğ‘€¼
- ğ‘€œğ‘†
- ğ‘€¯ğ‘„
- ğ‘€¢ğ‘€½
- ğ‘€§ğ‘€»
- ğ‘€¢ğ‘„
- ğ‘€
- ğ‘€˜ğ‘€½
- ğ‘€®ğ‘€¸
- ğ‘€“ğ‘…
- ğ‘€¦ğ‘€½
- ğ‘€«ğ‘€½
- ğ‘€œğ‘€¸
- ğ‘€§ğ‘ƒ
- ğ‘€ğ‘€½
- ğ‘€˜ğ‘„
- ğ‘€¡ğ‘€¸
- ğ‘€“ğ‘€»
- ğ‘€œ
- ğ‘€¬ğ‘„
- ğ‘€­ğ‘„
- ğ‘€˜ğ‘€»
- ğ‘€¯ğ‘†
- ğ‘€¬ğ‘‚
